name: iTrekkingIF
version: 1.0-SNAPSHOT
description: This is a simple Bukkit Plugin
author: Rodrigo Sanches Devigo

main: io.github.rsdevigo.Main

commands:
  Hello:
    description: Shows a hello message to the player
    usage: |
      /<command> shows a hello message to the player